server:
  port: 8090
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.1:8848
      config:
        server-addr: 192.168.56.1:8848
        namespace: 2bec1cc5-c2cd-4751-a603-2ccc3f30bf96
        group: DEV
        file-extension: yaml
  application:
    name: gulimall-member
  config:
    import:
      - nacos:datasource
      - nacos:mybatis-plus
