server:
  port: 9010
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.1:8848
      config:
        server-addr: 192.168.56.1:8848
        namespace: 7dc3a04e-a8e0-4a5e-ab08-2506d655d0e0
        group: DEV
        file-extension: yaml
  config:
    import:
      - nacos:datasource
      - nacos:mybatis-plus
  application:
    name: gulimall-product

