server:
  port: 8080
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.1:8848
      config:
        server-addr: 192.168.56.1:8848
        namespace: f0edc21e-a3d1-4594-b4bd-29f54d0b6f6a
        group: DEV
        file-extension: yaml
  config:
    import:
      - nacos:datasource
      - nacos:mybatis-plus
  application:
    name: gulimall-coupon
